### ISSUE TITLE
Games not accepting input

### ISSUE THREAD

**Issue by araghon007** [araghon007/X1nput#5]
A lot of games I tested don't accept controller input if the controller is connected before the game starts. A few games also crash when the controller gets disconnected. Sadly, it's exactly the games I can't debug.

**Comment by buzzcola107** [comment]
I do not know if it's the right place for, but ...
I teste some games with your new version 2.0, if it can helped you a little ?
I have Windows 10 Enterprise LTSC 1809.
I only use my controller with wireless dongle (I do not know if it changes something).

64-bit Games

work :
Metro Exodus
Assassin's Creed Origine 
Assassin's Creed Odysser
Hitman 2
Dying Light - The Following
Earthfall Invasion
Need For Speed
Dirt Rally 2.0
Fallout 4
Final Fantasy XV

Game work but controller not respond, need to turn off/on the controller in game and all work :
Doom 2016
GTA 5
Resident Evil 2
Gravel
Just Cause 4

Don't work :
Far Cry New Down
Call of Duty - WWII, (*work with v1.3*, with v2.0 controller not respond and turn  off/on the controller change nothing)

Crash :
Dead or Alive 6
Devil May Cry 5, (weird because it uses Resident Evil 2 engine)


32-bit Games

work :
Crysis 
Far Cry 3 Blood Dragon

Crash :
*Borderland 2 (*work with all previous version...* with v2.0 the game crash)*
Catherine Classic (game start but not work with 1.3, with v2.0 the game crash)
Sonic & All Stars Racing Transformed (game start but not work with 1.3 and under, with v2.0 the game crash)


-----------------------------------------------------------------------
2 games don't work anymore with v2.0 vs 1.3, but a lot of new games work on v2.0
More crash on 32-bit with v2.0 vs v1.3

Great improvement in a short time, good job and good luck !
(sorry for my bad english)

**Comment by araghon007** [comment]
Thanks!
I'll try some of the games that worked with previous version and see what causes the crashes. I'm also hoping I could resolve the issue with input soon

**Comment by r57zone** [comment]
I found a trick how to integrate this into almost any game, for this you need to use injection.

Here you can see how to do it. 

https://github.com/r57zone/X360Advance
https://github.com/r57zone/XInputInjectDLL

**Comment by araghon007** [comment]
I should've listened to you earlier, man. Thanks a lot for XInputInjectDLL, I'll try not to give up on this project again this time
